# Generated by Django 4.0.1 on 2022-01-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
